info:
  contact: {}
  description: 该项目用于读取各种类型的文件
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: FILESYSY
  version: "1.0"
paths:
  /csv:
    get:
      description: 指定CSV文件获取数据
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "401":
          description: 失败
          schema:
            type: string
      summary: 获取CSV数据
      tags:
      - 获取CSV数据
  /excel:
    get:
      description: 指定excel文件获取数据
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "401":
          description: 失败
          schema:
            type: string
      summary: 获取excel数据
      tags:
      - 获取excel数据
  /ftp/:path:
    get:
      description: 获取FTP服务器文件信息
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "401":
          description: 失败
          schema:
            type: string
      summary: 获取FTP服务器文件信息
      tags:
      - 获取FTP服务器文件信息
  /getJson:
    post:
      description: 获取前端传来的JSON数据并返回
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "401":
          description: 失败
          schema:
            type: string
      summary: 获取前端传来的JSON数据
      tags:
      - 获取前端传来的JSON数据
  /json:
    get:
      description: 指定json文件获取数据
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "401":
          description: 失败
          schema:
            type: string
      summary: 获取json数据
      tags:
      - 获取json数据
  /txt:
    get:
      description: 指定txt文件获取数据
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "401":
          description: 失败
          schema:
            type: string
      summary: 获取txt数据
      tags:
      - 获取txt数据
  /xml:
    get:
      description: 指定xml文件获取数据
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "401":
          description: 失败
          schema:
            type: string
      summary: 获取xml数据
      tags:
      - 获取xml数据
swagger: "2.0"
